language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t nikolatrajkovski/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true nikolatrajkovski/docker-react npm run test
