language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t nikolatrajkovski/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true nikolatrajkovski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "docker-react1"
  bucket_name: "elasticbeanstalk-us-east-2-192066411076"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  


